#! /bin/sh

state=.SYNC-STATE

[ -r $state ] || touch -t 197102030405 $state
for f in *.lua; do
    [ $f -nt $state ] && /usr/bin/python2.7 ~/bin/luatool/luatool/luatool.py --port /dev/ttyUSB0 -b 115200 --src $f
done
touch $state
